const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.StopLoop,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{ustbar: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{isActive: 0},
	{prevBtn: 0},
	{nextBtn: 0},
	{arrow: 0},
	{solbar: 0},
	{sagbar: 0},
	{posX: 0},
	{posY: 0},
	{isPlaced: 0},
	{DragDrop: 0},
	{Tween: 0},
	{bond: 0},
	{levisNokta: 0},
	{levisKare: 0},
	{bilesik: 0},
	{isFirst: 0},
	{elementText: 0},
	{elementLevis: 0},
	{isAna: 0},
	{isYan: 0},
	{Flash: 0},
	{elementBtn: 0},
	{levisJSON: 0},
	{AJAX: 0},
	{verticalIndex: 0},
	{isBag: 0},
	{bagIndex: 0},
	{serbestElektronCiftIndex: 0},
	{example: 0},
	{randomArray: 0},
	{Browser: 0},
	{Sprite2: 0},
	{isFillArea: 0},
	{isPrivate: 0},
	{yan: 0},
	{ana: 0},
	{Touch: 0},
	{loaderEmpty: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{elementArea: 0},
	{CheckLevisKareStatu: 0},
	{gameStart: 0},
	{levelComplete: 0},
	{toplamBagSayisi: 0},
	{toplamSerbestElektronCifti: 0},
	{toplamElementSayisi: 0},
	{heightValue: 0},
	{result: 0},
	{lewisBagLoop: 0},
	{lewisElektronLoop: 0},
	{bagCount: 0},
	{lewisAlignLoop: 0},
	{isLoader: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	ustbar: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	arrow: class extends self.ISpriteInstance {},
	solbar: class extends self.ISpriteInstance {},
	sagbar: class extends self.ISpriteInstance {},
	bond: class extends self.ISpriteInstance {},
	levisNokta: class extends self.ISpriteInstance {},
	levisKare: class extends self.ISpriteInstance {},
	bilesik: class extends self.ISpriteInstance {},
	elementText: class extends self.ISpriteInstance {},
	elementLevis: class extends self.ISpriteInstance {},
	elementBtn: class extends self.ISpriteInstance {},
	levisJSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	example: class extends self.ISpriteInstance {},
	randomArray: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	yan: class extends self.ISpriteInstance {},
	ana: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	elementArea: class extends self.ISpriteInstance {}
}